#!/usr/bin/env ruby

require File.expand_path("../../spec/spec_helper", __FILE__)

dangerfile = testing_dangerfile
plugin = dangerfile.luacheck


allow_any_instance_of(Danger::DangerfileGitPlugin).to receive(:added_files).and_return(['app/src/main/java/com/mataku/Model.kt'])
allow_any_instance_of(Danger::DangerfileGitPlugin).to receive(:modified_files).and_return([])
 
allow_any_instance_of(Kernel).to receive(:system).with('which ktlint > /dev/null 2>&1').and_return(true)
allow_any_instance_of(Kernel).to receive(:`).with('ktlint app/src/main/java/com/mataku/Model.kt --reporter=json --relative').and_return(dummy_ktlint_result)

